-- MySQL Script generated by MySQL Workbench
-- Tue Mar 22 17:48:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ucon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ucon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ucon` DEFAULT CHARACTER SET utf8 ;
USE `ucon` ;

-- -----------------------------------------------------
-- Table `ucon`.`sexs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`sexs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sex` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sex_UNIQUE` (`sex` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `full_name` VARCHAR(64) NOT NULL,
  `lattes_id` VARCHAR(45) NULL,
  `birth_date` DATE NOT NULL,
  `sexs_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_users_sexs1_idx` (`sexs_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_sexs1`
    FOREIGN KEY (`sexs_id`)
    REFERENCES `ucon`.`sexs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ucon`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course` VARCHAR(255) NOT NULL COMMENT 'Cursos',
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `course_UNIQUE` (`course` ASC) INVISIBLE);


-- -----------------------------------------------------
-- Table `ucon`.`research_areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`research_areas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `research_area` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `research_area_UNIQUE` (`research_area` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`teachers` (
  `users_id` INT NOT NULL,
  `h_index` DECIMAL NULL,
  INDEX `fk_teachers_users_idx` (`users_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_teachers_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ucon`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`educational_institutions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`educational_institutions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `educational_institution` VARCHAR(255) NOT NULL,
  `acronym` VARCHAR(64) NULL,
  `socre` INT NULL COMMENT 'Socore de 0 a 100',
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`students` (
  `users_id` INT NOT NULL,
  `graduation_semester` INT NOT NULL,
  `educational_institutions_id` INT NOT NULL,
  `courses_id` INT NOT NULL,
  PRIMARY KEY (`users_id`),
  INDEX `fk_students_educational_institutions1_idx` (`educational_institutions_id` ASC) VISIBLE,
  INDEX `fk_students_courses1_idx` (`courses_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `ucon`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_educational_institutions`
    FOREIGN KEY (`educational_institutions_id`)
    REFERENCES `ucon`.`educational_institutions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `ucon`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`degrees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`degrees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `degree` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `degree_UNIQUE` (`degree` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`teachers_has_degrees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`teachers_has_degrees` (
  `teachers_users_id` INT NOT NULL,
  `degrees_id` INT NOT NULL,
  `educational_institutions_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`teachers_users_id`, `degrees_id`),
  INDEX `fk_teachers_has_degrees_degrees1_idx` (`degrees_id` ASC) VISIBLE,
  INDEX `fk_teachers_has_degrees_teachers1_idx` (`teachers_users_id` ASC) VISIBLE,
  INDEX `fk_teachers_has_degrees_educational_institutions1_idx` (`educational_institutions_id` ASC) VISIBLE,
  CONSTRAINT `fk_teachers_has_degrees_teachers1`
    FOREIGN KEY (`teachers_users_id`)
    REFERENCES `ucon`.`teachers` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teachers_has_degrees_degrees1`
    FOREIGN KEY (`degrees_id`)
    REFERENCES `ucon`.`degrees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teachers_has_degrees_educational_institutions1`
    FOREIGN KEY (`educational_institutions_id`)
    REFERENCES `ucon`.`educational_institutions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`scholarship_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`scholarship_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `scholarship_type` VARCHAR(64) NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `scholarship_types_id` INT NOT NULL,
  `teachers_users_id` INT NOT NULL,
  `openned` TINYINT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `fk_projects_scholarship_types1_idx` (`scholarship_types_id` ASC) VISIBLE,
  INDEX `fk_projects_teachers1_idx` (`teachers_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_scholarship_types1`
    FOREIGN KEY (`scholarship_types_id`)
    REFERENCES `ucon`.`scholarship_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_teachers1`
    FOREIGN KEY (`teachers_users_id`)
    REFERENCES `ucon`.`teachers` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`opportunities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`opportunities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projects_id` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  `semester_start` VARCHAR(45) NULL,
  `semester_end` VARCHAR(45) NULL,
  `openned` TINYINT NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`, `projects_id`),
  CONSTRAINT `fk_opportunity_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `ucon`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`matchs_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`matchs_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `match_status` VARCHAR(32) NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`matchs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`matchs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `opportunity_id` INT NOT NULL,
  `students_users_id` INT NOT NULL,
  `matchs_status_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`, `opportunity_id`, `students_users_id`),
  INDEX `fk_matchs_students1_idx` (`students_users_id` ASC) VISIBLE,
  INDEX `fk_matchs_opportunity1_idx` (`opportunity_id` ASC) VISIBLE,
  INDEX `fk_matchs_matchs_status1_idx` (`matchs_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_matchs_students1`
    FOREIGN KEY (`students_users_id`)
    REFERENCES `ucon`.`students` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchs_opportunity1`
    FOREIGN KEY (`opportunity_id`)
    REFERENCES `ucon`.`opportunities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchs_matchs_status1`
    FOREIGN KEY (`matchs_status_id`)
    REFERENCES `ucon`.`matchs_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`students_follow_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`students_follow_teachers` (
  `students_users_id` INT NOT NULL,
  `teachers_users_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`students_users_id`, `teachers_users_id`),
  INDEX `fk_students_has_teachers_teachers1_idx` (`teachers_users_id` ASC) VISIBLE,
  INDEX `fk_students_has_teachers_students1_idx` (`students_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_has_teachers_students1`
    FOREIGN KEY (`students_users_id`)
    REFERENCES `ucon`.`students` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_teachers_teachers1`
    FOREIGN KEY (`teachers_users_id`)
    REFERENCES `ucon`.`teachers` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`users_has_research_areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`users_has_research_areas` (
  `users_id` INT NOT NULL,
  `research_areas_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`users_id`, `research_areas_id`),
  INDEX `fk_users_has_research_areas_research_areas1_idx` (`research_areas_id` ASC) VISIBLE,
  INDEX `fk_users_has_research_areas_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_research_areas_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ucon`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_research_areas_research_areas1`
    FOREIGN KEY (`research_areas_id`)
    REFERENCES `ucon`.`research_areas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ucon`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(1024) NOT NULL,
  `author_id` INT NOT NULL,
  `matchs_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `fk_chats_users_idx` (`author_id` ASC) INVISIBLE,
  INDEX `fk_chats_matchs1_idx` (`matchs_id` ASC) VISIBLE,
  CONSTRAINT `fk_chats_users1`
    FOREIGN KEY (`author_id`)
    REFERENCES `ucon`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chats_matchs1`
    FOREIGN KEY (`matchs_id`)
    REFERENCES `ucon`.`matchs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ucon`.`opportunity_has_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ucon`.`opportunity_has_students` (
  `opportunity_id` INT NOT NULL,
  `students_users_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`opportunity_id`, `students_users_id`),
  INDEX `fk_opportunity_has_students_students1_idx` (`students_users_id` ASC) VISIBLE,
  INDEX `fk_opportunity_has_students_opportunity1_idx` (`opportunity_id` ASC) VISIBLE,
  CONSTRAINT `fk_opportunity_has_students_opportunity1`
    FOREIGN KEY (`opportunity_id`)
    REFERENCES `ucon`.`opportunities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opportunity_has_students_students1`
    FOREIGN KEY (`students_users_id`)
    REFERENCES `ucon`.`students` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
